parameter BUS_ADDR_CORE_HALT      =  'h400;
parameter BUS_ADDR_CORE_RESUME    =  'h404;
parameter BUS_ADDR_CORE_EXCEPTION =  'h408;
parameter BUS_ADDR_DM_REQUEST     =  'h420;

parameter DMI_ADDR_DATA0          = 7'h04;
parameter DMI_ADDR_DATA1          = 7'h05;
parameter DMI_ADDR_DMCONTROL      = 7'h10;
parameter DMI_ADDR_DMSTATUS       = 7'h11;


parameter DMCONTROL_HALTREQ_MSB          = 31;
parameter DMCONTROL_HALTREQ_LSB          = 31;
parameter DMCONTROL_RESUMEREQ_MSB        = 30;
parameter DMCONTROL_RESUMEREQ_LSB        = 30;
parameter DMCONTROL_HARTRESET_MSB        = 29;
parameter DMCONTROL_HARTRESET_LSB        = 29;
parameter DMCONTROL_ACKHAVERESET_MSB     = 28;
parameter DMCONTROL_ACKHAVERESET_LSB     = 28;
parameter DMCONTROL_HASEL_MSB            = 26;
parameter DMCONTROL_HASEL_LSB            = 26;
parameter DMCONTROL_HARTSELLO_MSB        = 25;
parameter DMCONTROL_HARTSELLO_LSB        = 16;
parameter DMCONTROL_HARTSELHI_MSB        = 15;
parameter DMCONTROL_HARTSELHI_LSB        =  6;
parameter DMCONTROL_SETRESETHALTREQ_MSB  =  3;
parameter DMCONTROL_SETRESETHALTREQ_LSB  =  3;
parameter DMCONTROL_CLRRESETHALTREQ_MSB  =  2;
parameter DMCONTROL_CLRRESETHALTREQ_LSB  =  2;
parameter DMCONTROL_NDMRESET_MSB         =  1;
parameter DMCONTROL_NDMRESET_LSB         =  1;
parameter DMCONTROL_DMACTIVE_MSB         =  0;
parameter DMCONTROL_DMACTIVE_LSB         =  0;

`define DMCONTROL_HALTREQ_RANGE           DMCONTROL_HALTREQ_MSB:DMCONTROL_HALTREQ_LSB
`define DMCONTROL_RESUMEREQ_RANGE         DMCONTROL_RESUMEREQ_MSB:DMCONTROL_RESUMEREQ_LSB
`define DMCONTROL_HARTRESET_RANGE         DMCONTROL_HARTRESET_MSB:DMCONTROL_HARTRESET_LSB
`define DMCONTROL_ACKHAVERESET_RANGE      DMCONTROL_ACKHAVERESET_MSB:DMCONTROL_ACKHAVERESET_LSB
`define DMCONTROL_HASEL_RANGE             DMCONTROL_HASEL_MSB:DMCONTROL_HASEL_LSB
`define DMCONTROL_HARTSELLO_RANGE         DMCONTROL_HARTSELLO_MSB:DMCONTROL_HARTSELLO_LSB
`define DMCONTROL_HARTSELHI_RANGE         DMCONTROL_HARTSELHI_MSB:DMCONTROL_HARTSELHI_LSB
`define DMCONTROL_SETRESETHALTREQ_RANGE   DMCONTROL_SETRESETHALTREQ_MSB:DMCONTROL_SETRESETHALTREQ_LSB
`define DMCONTROL_CLRRESETHALTREQ_RANGE   DMCONTROL_CLRRESETHALTREQ_MSB:DMCONTROL_CLRRESETHALTREQ_LSB
`define DMCONTROL_NDMRESET_RANGE          DMCONTROL_NDMRESET_MSB:DMCONTROL_NDMRESET_LSB
`define DMCONTROL_DMACTIVE_RANGE          DMCONTROL_DMACTIVE_MSB:DMCONTROL_DMACTIVE_LSB

`define DMCONTROL_HALTREQ_WIDTH           1
`define DMCONTROL_RESUMEREQ_WIDTH         1
`define DMCONTROL_HARTRESET_WIDTH         1
`define DMCONTROL_ACKHAVERESET_WIDTH      1
`define DMCONTROL_HASEL_WIDTH             1
`define DMCONTROL_HARTSELLO_WIDTH         10
`define DMCONTROL_HARTSELHI_WIDTH         10
`define DMCONTROL_SETRESETHALTREQ_WIDTH   1
`define DMCONTROL_CLRRESETHALTREQ_WIDTH   1
`define DMCONTROL_NDMRESET_WIDTH          1
`define DMCONTROL_DMACTIVE_WIDTH          1


parameter DMSTATUS_IMPEBREAK_MSB          = 22;
parameter DMSTATUS_IMPEBREAK_LSB          = 22;
parameter DMSTATUS_ALLHAVERESET_MSB       = 19;
parameter DMSTATUS_ALLHAVERESET_LSB       = 19;
parameter DMSTATUS_ANYHAVERESET_MSB       = 18;
parameter DMSTATUS_ANYHAVERESET_LSB       = 18;
parameter DMSTATUS_ALLRESUMEACK_MSB       = 17;
parameter DMSTATUS_ALLRESUMEACK_LSB       = 17;
parameter DMSTATUS_ANYRESUMEACK_MSB       = 16;
parameter DMSTATUS_ANYRESUMEACK_LSB       = 16;
parameter DMSTATUS_ALLNONEEXISTENT_MSB    = 15;
parameter DMSTATUS_ALLNONEEXISTENT_LSB    = 15;
parameter DMSTATUS_ANYNONEEXISTENT_MSB    = 14;
parameter DMSTATUS_ANYNONEEXISTENT_LSB    = 14;
parameter DMSTATUS_ALLUNAVAIL_MSB         = 13;
parameter DMSTATUS_ALLUNAVAIL_LSB         = 13;
parameter DMSTATUS_ANYUNAVAIL_MSB         = 12;
parameter DMSTATUS_ANYUNAVAIL_LSB         = 12;
parameter DMSTATUS_ALLRUNNING_MSB         = 11;
parameter DMSTATUS_ALLRUNNING_LSB         = 11;
parameter DMSTATUS_ANYRUNNING_MSB         = 10;
parameter DMSTATUS_ANYRUNNING_LSB         = 10;
parameter DMSTATUS_ALLHALTED_MSB          =  9;
parameter DMSTATUS_ALLHALTED_LSB          =  9;
parameter DMSTATUS_ANYHALTED_MSB          =  8;
parameter DMSTATUS_ANYHALTED_LSB          =  8;
parameter DMSTATUS_AUTHENTICATED_MSB      =  7;
parameter DMSTATUS_AUTHENTICATED_LSB      =  7;
parameter DMSTATUS_AUTHBUSY_MSB           =  6;
parameter DMSTATUS_AUTHBUSY_LSB           =  6;
parameter DMSTATUS_HASRESETHALTREQ_MSB    =  5;
parameter DMSTATUS_HASRESETHALTREQ_LSB    =  5;
parameter DMSTATUS_CONFSTRPTRVALID_MSB    =  4;
parameter DMSTATUS_CONFSTRPTRVALID_LSB    =  4;
parameter DMSTATUS_VERSION_MSB            =  3;
parameter DMSTATUS_VERSION_LSB            =  0;

`define DMSTATUS_IMPEBREAK_RANGE          DMSTATUS_IMPEBREAK_MSB:DMSTATUS_IMPEBREAK_LSB
`define DMSTATUS_ALLHAVERESET_RANGE       DMSTATUS_ALLHAVERESET_MSB:DMSTATUS_ALLHAVERESET_LSB
`define DMSTATUS_ANYHAVERESET_RANGE       DMSTATUS_ANYHAVERESET_MSB:DMSTATUS_ANYHAVERESET_LSB
`define DMSTATUS_ALLRESUMEACK_RANGE       DMSTATUS_ALLRESUMEACK_MSB:DMSTATUS_ALLRESUMEACK_LSB
`define DMSTATUS_ANYRESUMEACK_RANGE       DMSTATUS_ANYRESUMEACK_MSB:DMSTATUS_ANYRESUMEACK_LSB
`define DMSTATUS_ALLNONEEXISTENT_RANGE    DMSTATUS_ALLNONEEXISTENT_MSB:DMSTATUS_ALLNONEEXISTENT_LSB
`define DMSTATUS_ANYNONEEXISTENT_RANGE    DMSTATUS_ANYNONEEXISTENT_MSB:DMSTATUS_ANYNONEEXISTENT_LSB
`define DMSTATUS_ALLUNAVAIL_RANGE         DMSTATUS_ALLUNAVAIL_MSB:DMSTATUS_ALLUNAVAIL_LSB
`define DMSTATUS_ANYUNAVAIL_RANGE         DMSTATUS_ANYUNAVAIL_MSB:DMSTATUS_ANYUNAVAIL_LSB
`define DMSTATUS_ALLRUNNING_RANGE         DMSTATUS_ALLRUNNING_MSB:DMSTATUS_ALLRUNNING_LSB
`define DMSTATUS_ANYRUNNING_RANGE         DMSTATUS_ANYRUNNING_MSB:DMSTATUS_ANYRUNNING_LSB
`define DMSTATUS_ALLHALTED_RANGE          DMSTATUS_ALLHALTED_MSB:DMSTATUS_ALLHALTED_LSB
`define DMSTATUS_ANYHALTED_RANGE          DMSTATUS_ANYHALTED_MSB:DMSTATUS_ANYHALTED_LSB
`define DMSTATUS_AUTHENTICATED_RANGE      DMSTATUS_AUTHENTICATED_MSB:DMSTATUS_AUTHENTICATED_LSB
`define DMSTATUS_AUTHBUSY_RANGE           DMSTATUS_AUTHBUSY_MSB:DMSTATUS_AUTHBUSY_LSB
`define DMSTATUS_HASRESETHALTREQ_RANGE    DMSTATUS_HASRESETHALTREQ_MSB:DMSTATUS_HASRESETHALTREQ_LSB
`define DMSTATUS_CONFSTRPTRVALID_RANGE    DMSTATUS_CONFSTRPTRVALID_MSB:DMSTATUS_CONFSTRPTRVALID_LSB
`define DMSTATUS_VERSION_RANGE            DMSTATUS_VERSION_MSB:DMSTATUS_VERSION_LSB

`define DMSTATUS_IMPEBREAK_WIDTH          1
`define DMSTATUS_ALLHAVERESET_WIDTH       1
`define DMSTATUS_ANYHAVERESET_WIDTH       1
`define DMSTATUS_ALLRESUMEACK_WIDTH       1
`define DMSTATUS_ANYRESUMEACK_WIDTH       1
`define DMSTATUS_ALLNONEEXISTENT_WIDTH    1
`define DMSTATUS_ANYNONEEXISTENT_WIDTH    1
`define DMSTATUS_ALLUNAVAIL_WIDTH         1
`define DMSTATUS_ANYUNAVAIL_WIDTH         1
`define DMSTATUS_ALLRUNNING_WIDTH         1
`define DMSTATUS_ANYRUNNING_WIDTH         1
`define DMSTATUS_ALLHALTED_WIDTH          1
`define DMSTATUS_ANYHALTED_WIDTH          1
`define DMSTATUS_AUTHENTICATED_WIDTH      1
`define DMSTATUS_AUTHBUSY_WIDTH           1
`define DMSTATUS_HASRESETHALTREQ_WIDTH    1
`define DMSTATUS_CONFSTRPTRVALID_WIDTH    1
`define DMSTATUS_VERSION_WIDTH            4
